---

# Playbook - All

- hosts: cloudian
  vars:
    # s3 and s3-admin details are defined
    # in group_vars/cloudian.yml
    cluster:
      region: eu-1

    cmc_groups:
      - groupA
      - groupB

    cmc_users:
      user1:
        group: groupA
        cmc_pass: public
        fullname: User 1
        type: User
        bucket: bucket1
      user2:
        group: groupB
        cmc_pass: public
        fullname: User 2
        type: User
        bucket: bucket2

    storage_policies:
      rf_3:
        rf: 3
        default: True

  roles:
    - group
    - user
    - policy
    - buckets
