---

# Playbook - Storage Policy

- hosts: cloudian
  vars:
    # s3 and s3-admin details are defined
    # in group_vars/cloudian.yml
    cluster:
      region: eu-1

    storage_policies:
      rf_3:
        default: True

  roles:
    - policy
